### ISSUE TITLE
Implantação do Kibana

### ISSUE THREAD

**Issue by guilacerda** [proepidesenvolvimento/guardioes-web#4]
**Descrição**

O Kibana é o serviço da ElasticStack responsável por disponibilizar ferramentas para o desenvolvimento de dashboards, visualizações, gráficos e outros. Os dados são consumidos do ElasticSearch e é possível através de querys (do próprio elastic) fazer buscas e mostrar em tempo real a evolução dos dados.

O próprio Kibana permite o compartilhamento de seus dashboards em sites de terceiros através de iframes, com diversos níveis de permissão.

**Tarefas**

- [ ] Estudar quais visualizações serão necessárias para o contexto do Guardiões.
- [ ] Implantar o Kibana em produção.
- [ ] Criar níveis de permissão para usuários distintos no Kibana

**Critérios de aceitação**

- [ ] É possível criar dashboards e visualizações a partir dos dados armazenados no ElasticSearch.
- [ ] O usuário administrador consegue criar, deletar e compartilhar os dashboards e visualizações.
- [ ] O usuário de negócio consegue apenas visualizar as informações dispostas nos dashboards e visualizações.
- [ ] É possível exportar o iframe dos dashboards em outra plataforma web.

**Comment by guilacerda** [comment]
Segue abaixo o link para a documentação do Kibana. 

https://www.elastic.co/guide/en/kibana/current/getting-started.html

A partir da versão 7.x é possível fazer a distinção dos usuários em diferentes níveis.

**Comment by guilacerda** [comment]
Sugiro a criação de uma issue para cada visualização que seja decidida implementar.
